version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - AZURE_CONNECTION_STRING=${AZURE_CONNECTION_STRING}
      - AZURE_CONTAINER_NAME=${AZURE_CONTAINER_NAME}
      - BACKBLAZE_ACCESS_KEY_ID=${BACKBLAZE_ACCESS_KEY_ID}
      - BACKBLAZE_SECRET_ACCESS_KEY=${BACKBLAZE_SECRET_ACCESS_KEY}
      - BACKBLAZE_BUCKET_NAME=${BACKBLAZE_BUCKET_NAME}
      - BACKBLAZE_S3_ENDPOINT_URL=${BACKBLAZE_S3_ENDPOINT_URL}
      - CONSIDER_OLD_AFTER_HRS=${CONSIDER_OLD_AFTER_HRS}
